version: '3.9'
services:
  parsedmarc:
    build: ./parsedmarc/
    volumes:
      - ./parsedmarc/files:/input:ro
      - ./parsedmarc/output_files:/output
      - ./parsedmarc/parsedmarc.ini:/parsedmarc.ini
    command: parsedmarc --debug -c /parsedmarc.ini /input/*
    depends_on:
      elasticsearch:
        condition: service_healthy      
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  grafana:
    restart: on-failure
    build: ./grafana/
    ports:
      - 3001:3001
    user: root
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-worldmap-panel
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
volumes:
  elasticsearch_data: